package sop_corba;


/**
* sop_corba/ObtenerEstadisticasInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from operaciones.idl
* jueves 8 de junio de 2023 03:12:55 PM COT
*/

public interface ObtenerEstadisticasInt extends ObtenerEstadisticasIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ObtenerEstadisticasInt
